### ISSUE TITLE
[Question]: How do I get $ref: #/components/schemas/SchemaName in YAML output

### ISSUE THREAD

**Issue by DerekStrickland** [getkin/kin-openapi#381]
Hi!

First, thanks for the amazing library. This has truly been a huge time saver for me personally.

I've got a lack of knowledge on something though. I am using the suggested YAML package, and I'm setting a property ref like this

`schema.WithPropertyRef(field.Name(), ref)`

My output ends up having the full schema for the embedded type inlined. I'd rather have one schema defined and have other schemas reference it like 

`JobSummary:
  $ref: #/components/schemas/JobSummary
`

Is there a way to do that?

**Comment by fenollp** [comment]
Thanks for the kind words!

Are you maybe missing a call to https://github.com/getkin/kin-openapi/blob/d30837871e4548501ae7e3fc9ed0f74e35caa53d/openapi3/loader.go#L182 right before serialization?
Are you sure `schema.Ref != ""`? When serializing (at least with JSON) the `.Ref` part is taken instead of the `.Value` part.

If you can manage a minimal test program I can help. I'm time starved here.

**Comment by DerekStrickland** [comment]
Thanks for the pro-tip!  This got me unstuck! When I get the code production ready, I'll share so you can add us to your list of projects using Kin.  Thanks again!  Great project, and a great implementation.
