### ISSUE TITLE
Readme for OpenApi3

### ISSUE THREAD

**Issue by jslota-rt** [getkin/kin-openapi#446]
Any chance we could get a readme going for openapi3? I am new to open api and swagger and finding it pretty difficult to add the new openapi3 to my go microservice, would be great if there was a beginners readme for openapi3 to get it going in a new project, thank you

**Comment by fenollp** [comment]
Are you aware of https://pkg.go.dev/github.com/getkin/kin-openapi/openapi3?
I'm sure this is missing code examples however.
What functionalities are you looking for? Maybe you can tell us more about what you're trying to do.

**Comment by philsturgeon** [comment]
Hey if you're looking for an easier way to do things, annotations are probably not that. There are many other ways handle your OpenAPI which are more useful and enable design-first instead of flopping some generated OpenAPI out later on, which is missing half the useful context. https://apisyouwonthate.com/blog/theres-no-reason-to-write-openapi-by-hand
