### ISSUE TITLE
Resolved references do not get Ref property set

### ISSUE THREAD

**Issue by nialexander** [getkin/kin-openapi#464]
Types that can be referenced are built like this:
```
type SchemaRef struct {
  Ref string
  Value *Schema
}
```

When I use references in the openapi file and load it (tried loading with `LoadFromFile` and unmarshaling with github.com/ghodss/yaml) the Ref property is empty. I'd exepct the Ref property to be set to the reference name (e.g. `#/components/schemas/ABCDE`.

Why do I need Ref to be set? 

I want to remove unused schemes from the file, therefore I need to check which references are still used.

**Comment by fenollp** [comment]
Structs such as 
```go
type SchemaRef struct {
  Ref string
  Value *Schema
}
```
actually represent unions over `Ref` and `Value` meaning usually only one of the fields would be set. When serializing, the `Ref` field is preferred if set:
```yaml
$ref: '#/bla/bla/bla'
```

From what I understand you are doing is expecting `Ref` to always be set so as to check for existence in a large map-like structure, when actually `Value` is non-nil.
Maybe you expect all schemas to be defined in `/components/schemas/*` and everywhere else referenced with `$ref`? In this case `Ref` would be non-zero for every `SchemaRef` not under components and the existence check would work. This functionality requires an `(*Schema)Equal(*Schema)` method but I guess `reflect.DeepEqual` should do.

Tree-shaking schemas is an interesting idea & I would love to review a PR that adds this :)

If you can manage to extract the schema visitor that you will need for this so that it is reusable by others, I'm sure the community will appreciate this very much.

**Comment by nialexander** [comment]
Thanks for your fast answer!

> usually only one of the fields would be set

Yeah that is where my assumptions were wrong. I assumed both fields would be set. 

For now I found a workaround by simply doing a regex search through the whole document to find non used refs. Maybe I will come back to this later and find a better and more general solution.
