### ISSUE TITLE
Responses object doesn't support extensions

### ISSUE THREAD

**Issue by TristanSpeakEasy** [getkin/kin-openapi#687]
According to the OpenAPI Spec the `responses` object should be able to have extensions added to it https://spec.openapis.org/oas/v3.0.3#responses-object `This object MAY be extended with [Specification Extensions](https://spec.openapis.org/oas/v3.0.3#specificationExtensions).`

But the latest version of kin-openapi doesn't expose extensions for the `openapi3.Responses` type which at the moment looks to be just a type alias to a map

**Comment by fenollp** [comment]
Correct! `Responses` should be turned into a 
```go
struct {
	Extensions map[string]interface{} `json:"-"`

	map[string]*ResponseRef `json:"responses"`
}
```
with custom Un/MarshalJSON implementations. I'm in the middle of https://github.com/getkin/kin-openapi/issues/513 but that work should make the fix for this issue easier.

Also https://github.com/getkin/kin-openapi/blob/46e0df8ae84cbb51b7c672a0bb8ebb6995d28c7a/openapi3/response.go#L31-L33 needs to try `21X` and `2XX` type fields...
