### ISSUE TITLE
earlier circular reference detection

### ISSUE THREAD

**Issue by maciej** [getkin/kin-openapi#766]
Given a circular reference between two components I'd expect it to be detected when a first cycle appears in the reference traversal stack, so in the example linked here:

https://go.dev/play/p/0QT2aV29OSF

I'd expect to see:

```
circular schema reference not handled - #/components/schemas/loop-endless -> #/components/schemas/endless-loop -> #/components/schemas/loop-endless
```

without the additional cycle mentioned in the error message.

**Comment by radwaretaltr** [comment]
Hi, you can modify the CircularReferenceCounter and set it to 2.
https://pkg.go.dev/github.com/getkin/kin-openapi/openapi3#:~:text=var%20CircularReferenceCounter%20%3D%203

**Comment by radwaretaltr** [comment]
> Hi, you can modify the CircularReferenceCounter and set it to 2. https://pkg.go.dev/github.com/getkin/kin-openapi/openapi3#:~:text=var%20CircularReferenceCounter%20%3D%203

I wouldn't recommend it though. The "CircularReferenceCounter" name is a bit misleading. It actually counts how many time the loader visited a schema reference. There are valid cases in which you will need to actually raise the value of "CircularReferenceCounter" in order to load the schema successfully.

**Comment by AnatolyRugalev** [comment]
`CircularReferenceCounter` and the mentioned error message has been removed in #970, so the issue doesn't seem to be relevant anymore
