### ISSUE TITLE
invalid components error when response schema contains additionalProperties

### ISSUE THREAD

**Issue by anjaliSeven** [getkin/kin-openapi#772]
Given a specification with additional properties in the response schema, 
returns error **"invalid components: schema "schema1": extra sibling fields: [has schema]"**

example:
```
openapi: 3.0.0
info:
  title: "Service"
  version: 0.1.9
paths:
  /service:
    get:
      responses:
        "200":
          $ref: "#/components/responses/response1"

components:
  responses:
    response1:
      description: response data
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/schema1"

  schemas:
    schema1:
      properties:
        "":
          type: object
          additionalProperties:
            type: string
      type: object

**Comment by fenollp** [comment]
```yaml
# issue772.yml
openapi: 3.0.0
info:
  title: "Service"
  version: 0.1.9
paths:
  /service:
    get:
      responses:
        "200":
          $ref: "#/components/responses/response1"

components:
  responses:
    response1:
      description: response data
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/schema1"

  schemas:
    schema1:
      properties:
        "":
          type: object
          additionalProperties:
            type: string
      type: object
```

```shell
go run github.com/getkin/kin-openapi/cmd/validate@latest issue772.yml
# go: downloading github.com/getkin/kin-openapi v0.114.0
# ...
```
No issue.

**Comment by anjaliSeven** [comment]
Hi @fenollp as in v0.113.0 AdditionalProperties has been added with the additional field so the validation is failing for me after the marshalling. It would be very helpful if u can help in marshalling it properly.
```
func Test(t *testing.T) {
	before, err := os.ReadFile("issue772.yml")
	assert.NoError(t, err)

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	spec, err := loader.LoadFromData(before)
	assert.NoError(t, err)

	after, err := yaml.Marshal(spec)
	assert.NoError(t, err)
	f, err := os.Create("after.yml")
	assert.NoError(t, err)
	f.WriteString(string(after))

	doc, err := loader.LoadFromFile("after.yml")
	assert.NoError(t, err)
	err = doc.Validate(context.Background())
	assert.NoError(t, err)
}

--- FAIL: Test (0.00s)
 Error:      	Received unexpected error:
        	            	invalid components: schema "schema1": extra sibling fields: [has schema]

**Comment by fenollp** [comment]
1. I have no idea what `yaml` package you're using
1. Print the problematic YAML file (the `after`), we should find your issue much faster.

**Comment by anjaliSeven** [comment]
```
package used:
#after.yml
openapi: 3.0.0
components:
    schemas:
        schema1:
            type: object
            properties:
                "":
                    type: object
                    additionalProperties:
                        has: null
                        schema:
                            type: string
    responses:
        response1:
            description: response data
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/schema1'
info:
    title: Service
    version: 0.1.9
paths:
    /service:
        get:
            responses:
                "200":
                    $ref: '#/components/responses/response1'

**Comment by anjaliSeven** [comment]
additionalProperties:
            type: string
 when converted to struct and then marshalled is changed to 
 additionalProperties:
                        has: null
                        schema:
                            type: string

**Comment by praneetloke** [comment]
I am seeing some weirdness too since v0.113.0 that I think is similar to the issue reported here. Specifically, the changes in https://github.com/getkin/kin-openapi/pull/728 seems to be triggering the error. For example, this path:

```yaml
paths:
  /owners:
    get:
      tags:
        - Owners
      summary: List authorized users and teams
      description: >-
        [https://api-docs.render.com/reference/get-owners](https://api-docs.render.com/reference/get-owners)
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: name
          in: query
          schema:
            type: string
          example: sed aliqua qui anim
        - name: email
          in: query
          schema:
            type: string
          example: sed aliqua qui anim
        - name: cursor
          in: query
          schema:
            type: string
          description: Cursor to begin retrieving entries for this query
          example: Lorem amet sin
        - name: limit
          in: query
          schema:
            type: integer
          description: Max number of items that can be returned
          example: 20
      responses:
        "200":
          description: OK
          headers:
            Content-Type:
              schema:
                type: string
                example: application/json
components:
  schemas:
    owner:
      title: "Owner"
      description: "The owner object represents an authorized user or team. The `type` property indicates if the owner is a user or team."
      type: object
      properties:
        id:
          description: The owner ID.
          readOnly: true
          type: string
        name:
          description: The name of the owner.
          type: string
        email:
          description: The email of the owner.
          type: string
        type:
          description: The type of the authorized user.
          type: string
          enum: ["user", "team"]
```

fails validation with the error:

```
invalid paths: invalid path /owners/{id}: invalid operation GET: extra sibling fields: [type]
```

And when that doc is parsed, the `SchemaRef` for `#/components/schemas/owner` looks like this:

![image](https://user-images.githubusercontent.com/1466314/221478938-11567b10-b7e4-4813-ad2b-970a29ba7b2e.png)

I am not sure how the `extra` slice is being populated on doc parse since I haven't done a deeper investigation into the parsing routine yet. I am also trying to understand the changes in https://github.com/getkin/kin-openapi/pull/728.

**Comment by fenollp** [comment]
Hi, sorry I haven't got much time to look into this right now.
I believe you are right, the issue comes from YAML serialization. The issue should be around this code: https://github.com/getkin/kin-openapi/blob/cb687bf864ca2b3c141f7883e5b16bd9e7b42379/openapi3/schema.go#L176-L193

A couple leads: json+yaml tags may need to be added to the struct. But I believe a better choice is to implement a `MarshalYAML` func.

@anjaliSeven You should be able to resolve your issue by replacing the YAML package you're using with `github.com/invopop/yaml`

@praneetloke Take a look around https://github.com/getkin/kin-openapi/blob/e53fe386960a0f532637da538535f22c9a9249e6/refs.sh#L81

**Comment by praneetloke** [comment]
@fenollp thanks for the tip! It turned out that my API spec was actually incorrect. The `type`  property is unnecessary when a `ref` is provided. There were other issues as well such as the `example` property appearing as a child of `schema` rather than a sibling. So it looks like "disallow unknown properties" is actually working as intended in my case at least.

**Comment by anjaliSeven** [comment]
@fenollp thanks for the suggestion , will try it

**Comment by anjaliSeven** [comment]
using ```github.com/invopop/yaml``` for marshalling doesn't provide same result as ```gopkg.in/yaml.v3``` for my usecase.

**Comment by fenollp** [comment]
> doesn't provide same result

Yes that's the point. Show us the diff and be helpful.

**Comment by anjaliSeven** [comment]
@fenollp when marshalled with Invopop, one of the fields returns null. I haven't investigated the reason yet, so I haven't shared any examples. I will share them once I complete my investigation.

**Comment by fenollp** [comment]
@anjaliSeven Heya, okay. Please reopen this once you do :)
